import styled from "@emotion/styled";
import React, { useState, useEffect } from "react";
import Emotions from "./Emotions";
import Thoughts from "./Thoughts";
import { validateNodeData } from "./nodeFormValidation";
import Tips from "./Tips";
import { DataOperation } from "./constants";
import { ObjectId } from 'bson';

export const StyledWrapper = styled("div")({
  position: "fixed",
  top: 0,
  bottom: 0,
  right: 0,
  left: 0,
  backgroundColor: "white",
  width: "700px",
  height: "480px",
  margin: "auto",
  padding: 15,
  borderRadius: 8,
  boxShadow: "0px 0px 8px rgba(0, 0, 0, 0.2)",
  userSelect: "none",
});

export const Header = styled("div")({
  fontWeight: "bold",
  fontSize: 17,
  marginBottom: 10,
});

export const Inputs = styled("input")({
  width: "300px",
  padding: "4px 10px",
  borderRadius: 7,
  border: "1px solid rgba(0, 0, 0, 0.1)",
});

const DescriptionInput = styled("textarea")({
  width: "calc(100% - 6px)",
  height: "180px",
  resize: "none",
  padding: "4px 10px",
  borderRadius: 7,
  border: "1px solid rgba(0, 0, 0, 0.1)",
  marginBottom: 10,
});

export const SubmitButton = styled(Inputs)<{ isNodeDataDuplicate: boolean }>(
  ({ isNodeDataDuplicate }) => ({
    position: "absolute",
    bottom: 50,
    left: 20,
    backgroundColor: "white",
    cursor: isNodeDataDuplicate ? "not-allowed" : "pointer",
    fontWeight: "bold",
    color: isNodeDataDuplicate ? "rgba(0, 0, 0, 0.3)" : "black",
    border: isNodeDataDuplicate
      ? "2px solid rgba(0, 0, 0, 0.3)"
      : "1px solid rgba(0, 0, 0, 0.1)",
    ":hover": {
      backgroundColor: isNodeDataDuplicate ? "" : "rgb(192, 192, 192, 0.3)",
    },
  })
);

export const CancelButton = styled(Inputs)({
  position: "absolute",
  bottom: 50,
  right: 20,
  cursor: "pointer",
  backgroundColor: "white",
  fontWeight: "bold",
  transition: "all ease 300ms",
  ":hover": {
    backgroundColor: "rgb(192, 192, 192, 0.3)",
  },
});

export const StyledDiv = styled("div")({
  position: "fixed",
  top: 0,
  height: "100%",
  width: "100%",
  backdropFilter: "blur(10px)",
});

const StyledErrors = styled("div")<{ isEarlySubmit: boolean }>(
  ({ isEarlySubmit }) => ({
    color: isEarlySubmit ? "red" : "teal",
    fontSize: 12,
    marginBottom: 10,
  })
);

const StyledContainer = styled("div")({
  height: 350,
  padding: "10px 20px",
  backgroundColor: "rgba(242, 242, 242, 0.4)",
  borderRadius: 8,
  overflowY: "scroll",
  "::-webkit-scrollbar": {
    width: 12,
  },
  "::-webkit-scrollbar-track": {
    borderRadius: 8,
  },
  "::-webkit-scrollbar-thumb": {
    background: "rgba(165, 165, 165, 1)",
    borderRadius: 10,
  },
});

const StyledSlider = styled("input")({
  cursor: "pointer",
  marginBottom: 10,
});

interface Props {
  setShowNodeForm: any;
  savedData: NodeDataType[];
  setSavedData: any;
  setIsChartAdded: any;
  nodeData: NodeDataType;
  setNodeData: any;
  isDemoActive: boolean;
  hackedNodeData: NodeDataType;
  setHackedNodeData: any;
  userInfo: { username: string; email: string };
  isLoggedIn: boolean;
}

export interface Emotion {
  neutral?: number;
  fear?: number;
  joy?: number;
  anticipation?: number;
  trust?: number;
  anger?: number;
  surprise?: number;
  sadness?: number;
}

interface Thought {
  creative?: boolean;
  concrete?: boolean;
  abstract?: boolean;
  analytical?: boolean;
  critical?: boolean;
  unknown?: boolean;
}

export interface NodeDataType {
  thoughts: Thought;
  emotions: Emotion;
  priority: number;
  description: string;
  _id?: string; //because _id generated by mongodb
}

export interface NodeFormErrorType {
  thoughtsError: string;
  emotionsError: string;
  descriptionError: string;
}

const NodeForm: any = (props: Props) => {
  const {
    setShowNodeForm,
    setSavedData,
    setIsChartAdded,
    nodeData,
    setNodeData,
    savedData,
    isDemoActive,
    hackedNodeData,
    setHackedNodeData,
    userInfo: { email },
    isLoggedIn,
  } = props;

  const [nodeFormErrors, setNodeFormErrors] = useState({
    thoughtsError: "",
    emotionsError: "",
    descriptionError: "",
  });
  const [isNodeDataDuplicate, setIsNodeDataDuplicate] = useState(false);
  const [isEarlySubmit, setIsEarlySubmit] = useState(false);

  const refreshNodeData = () => {
    setNodeData(() => {
      return {
        thoughts: {},
        emotions: {},
        priority: 20,
        description: "",
        _id: new ObjectId("")

      };
    });
  };

  const refreshFormErrors = () => {
    setNodeFormErrors(() => {
      return {
        thoughtsError: "",
        emotionsError: "",
        descriptionError: "",
      };
    });
  };

  useEffect(() => {
    validateNodeData(nodeData, setNodeFormErrors);
    if (hackedNodeData) {
      setIsNodeDataDuplicate(
        JSON.stringify(hackedNodeData) === JSON.stringify(nodeData)
      );
    }
    return () => {};
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [nodeData]);

  const handleCancel = () => {
    setShowNodeForm(false);
    refreshNodeData();
    refreshFormErrors();
    setIsEarlySubmit(false);
  };

  const handleChange = (e: any) => {
    setNodeData((nodeData: NodeDataType) => {
      const { type, value, name, id } = e.target;

      // Handles thought change
      if (type === "checkbox") {
        return {
          ...nodeData,
          thoughts: {
            ...nodeData.thoughts,
            [id]: (e.target as HTMLInputElement).checked ? true : undefined,
          },
        };
      }

      // Handles priority change
      if (name === "priority") {
        return {
          ...nodeData,
          [name]: Number(value),
        };
      }

      // Handles description change
      return {
        ...nodeData,
        [name]: value,
      };
    });
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    if (!validateNodeData(nodeData, setNodeFormErrors)) {
      setIsEarlySubmit(true);
      return;
    }

    if (isNodeDataDuplicate) return;

    if (hackedNodeData) {
      const newSavedData = savedData.filter(
        (d) => JSON.stringify(d) !== JSON.stringify(hackedNodeData)
      );
      setSavedData(() => {
        return [...newSavedData, nodeData];
      });
    } else {
      setSavedData((prev: NodeDataType[]) => {
        return [...prev, nodeData];
      });
    }

    console.log(nodeData)
    if (isLoggedIn) {
      fetch(process.env.REACT_APP_MODIFY_DATA_API!, {
        method: "post",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          email,
          toBeAdded: nodeData,
          toBeDeleted: hackedNodeData,
          operation: hackedNodeData ? DataOperation.UPDATE : DataOperation.ADD,
        }),
      })
        .then((response) => response.json())
        //do something if error comes for example delete and inform the user
        .then((data) => {});
    }

    setHackedNodeData(null);
    refreshNodeData();
    refreshFormErrors();
    setShowNodeForm(false);
    setIsChartAdded(false);
    setIsEarlySubmit(false);
  };

  useEffect(() => {
    if (!isDemoActive && !isLoggedIn) {
      window.localStorage.setItem("savedData", JSON.stringify(savedData));
    }
  }, [isDemoActive, isLoggedIn, savedData]);

  return (
    <StyledDiv>
      <StyledWrapper>
        <form onSubmit={handleSubmit}>
          <StyledContainer>
            <Header>Description</Header>
            <DescriptionInput
              placeholder="Description"
              name="description"
              value={nodeData.description}
              onChange={handleChange}
            />
            {nodeFormErrors.descriptionError && (
              <StyledErrors isEarlySubmit={isEarlySubmit}>
                {nodeFormErrors.descriptionError}
              </StyledErrors>
            )}
            <Header>Thoughts</Header>
            <Thoughts nodeData={nodeData} handleChange={handleChange} />
            {nodeFormErrors.thoughtsError && (
              <StyledErrors isEarlySubmit={isEarlySubmit}>
                {nodeFormErrors.thoughtsError}
              </StyledErrors>
            )}
            <Header>Emotions</Header>
            <Emotions nodeData={nodeData} setNodeData={setNodeData} />
            {nodeFormErrors.emotionsError && (
              <StyledErrors isEarlySubmit={isEarlySubmit}>
                {nodeFormErrors.emotionsError}
              </StyledErrors>
            )}
            <Header>Priority</Header>
            <StyledSlider
              type="range"
              min="10"
              max="70"
              name="priority"
              onChange={handleChange}
              value={nodeData.priority}
            />
          </StyledContainer>
          <SubmitButton
            isNodeDataDuplicate={isNodeDataDuplicate}
            type="submit"
            value="Submit"
          />
          <CancelButton type="button" value="Cancel" onClick={handleCancel} />
        </form>
        <Tips />
      </StyledWrapper>
    </StyledDiv>
  );
};

export default NodeForm;
